services:
  db:
    image: mariadb
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: peerlink
      MARIADB_USER: peerlink
      MARIADB_PASSWORD: peerlink
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"
    networks:
      - peerlink
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+pymysql://peerlink:peerlink@db:3306/peerlink
    ports:
      - "8000:8000"
    volumes:
      - abstract_data:/app/data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - peerlink

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - peerlink


networks:
  peerlink:

volumes:
  db_data:
  abstract_data:
