CREATE DATABASE IF NOT EXISTS peerlink
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'peerlink'@'%' IDENTIFIED BY 'peerlink';
GRANT ALL PRIVILEGES ON peerlink.* TO 'peerlink'@'%';
FLUSH PRIVILEGES;

USE peerlink;

CREATE TABLE IF NOT EXISTS abstracts (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  gf_entry_id   VARCHAR(64) UNIQUE,
  data          JSON NOT NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS jobs (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  data          JSON NOT NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
